server:
  port: 8082

dubbo:
  application:
    name: dubbo-provider
  protocol:
    name: dubbo
    host: 127.0.0.1
    port: 20880
  registry:
    protocol: zookeeper
    address: 127.0.0.1
    port: 2181

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/middlestage?allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=UTF-8&characterSetResults=UTF-8
    username: root
    password: root
    cachePrepStmts: true
    prepStmtsSize: 250
    prepStmtsCacheSqlLimit: 2048
    userServerPrepStmts: true

  http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true

