server:
  port: 8080

dubbo:
  application:
    name: dubbo-consumer
  protocol:
    name: dubbo
    host: 127.0.0.1
    port: 20880
  registry:
    protocol: zookeeper
    address: 127.0.0.1
    port: 2181